title: "infra-lab — DevOps Pipeline"
description: "12-week DevOps project documenting a production-grade pipeline"
remote_theme: just-the-docs/just-the-docs

url: "https://lionelpinheiroduarte.github.io"
baseurl: "/infra-lab"

# Just the Docs configuration
search_enabled: true
heading_anchors: true

aux_links:
  "GitHub Repository":
    - "https://github.com/LionelPinheiroDuarte/infra-lab"

nav_sort: case_insensitive

callouts_level: quiet
callouts:
  note:
    color: blue
  warning:
    color: yellow

plugins:
  - jekyll-include-cache

footer_content: "infra-lab DevOps Pipeline — Lionel Pinheiro Duarte"
